### ISSUE TITLE
Issue in the README.md 

### ISSUE THREAD

**Issue by lenninlc** [dhairy-online/tts_rust#4]
I just noticed that the examples in the README.md have some mistakes. Hope it helps 

`use tts_rust::tts::GTTSClient;
use tts_rust::languages::Languages;

fn main() {
    let narrator: GTTSClient = GTTSClient {
        volume: 1.0, 
        language: Languages::English, // use the Languages enum
        tld: "com"
    };
    narrator.speak("Hello, World! my name is charles. How's everyone doing?").unwrap();
}

use tts_rust::tts::GTTSClient;
use tts_rust::languages::Languages;

fn main() {
    let mut narrator: GTTSClient = GTTSClient {
        volume: 1.0,
        language: Languages::English,
        tld: "com"
    };
    narrator.speak("Starting test?").unwrap();
    let ms = std::time::Duration::from_millis(1000);
    for _x in 1..9 {
        narrator.volume += 1.0;
        let to_speak: String = String::from("Loop ") + &narrator.volume.to_string();
        narrator.speak(&to_speak).unwrap();
        std::thread::sleep(ms);
    }
}`

Great project btw !

**Comment by AuracleTech** [comment]
Your code snippet is broken
```rs
use tts_rust::languages::Languages;
use tts_rust::tts::GTTSClient;

fn main() {
    let narrator: GTTSClient = GTTSClient {
        volume: 1.0,
        language: Languages::English,
        tld: "com",
    };
    narrator
        .speak("Hello, World! How's everyone doing?")
        .unwrap();
}
```

**Comment by nytly0** [comment]
Fixed
